name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Validate package
        uses: datakrama/archlinux-package-action@v1
        with:
          path: archpkg/PKGBUILD
          flags: '-si --noconfirm'
          namcap: false
